export const auditInfo = {
  isDraft: true,
  auditType: "",
  auditTypeId: "",
  system: [],
  auditors: [],
  location: "",
  auditNumber: "",
  auditYear: "",
  auditName: "",
  date: "",
  scheduleDate:"",
  auditedEntity: "",
  auditees: [],
  auditTemplate: "",
  auditScheduleId: "No Schedule",
  auditedClauses: [{ item: {} }],
  auditedDocuments: [{ item: {} }],
  checklist: [],
  selectedTemplates: [],
  sections: [],
  goodPractices: "",
};
